[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "amazon-pay-v2"
version = "0.0.4"
dependencies = [
  "requests",
  "cryptography",
]
requires-python = ">=3.7"
authors = [
  {name = "Hatraco GmbH", email = "webdev@hatraco.de"},
]
readme = "README.md"
[project.urls]
Repository = "https://github.com/Hatraco-GmbH/amazon-pay-v2"